name: Cancel
on:
  workflow_run:
    id: gatekeeper
    workflows: [ "Gatekeeper" ]
    types:
      - completed
jobs:
  cancel:
    name: 'Cancel Previous Runs'
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action
        with:
          workflow_id: >-
            add-ci-passed-label.yml,
            api-server-tests.yml,
            backend-visualization.yml,
            build-and-push.yml,
            build-and-push-test-image.yml,
            build-images.yaml,
            build-master.yml,
            build-prs.yml,
            build-prs-trigger.yaml,
            build-tools-images.yml,
            ci-checks.yml,
            codeql.yml,
            commit-check-pr.yml,
            compiler-tests.yml,
            create-manifest.yml,
            e2e-test.yml,
            e2e-test-frontend.yml,
            frontend.yml,
            gcpc-modules-tests.yml,
            gh-workflow-approve.yml,
            image-builds.yml,
            image-builds-master.yml,
            image-builds-release.yml,
            integration-tests-v1.yml,
            kfp-kubernetes-library-test.yml,
            kfp-kubernetes-native-migration-tests.yaml,
            kfp-sdk-client-tests.yml,
            kfp-sdk-tests.yml,
            kfp-sdk-unit-tests.yml,
            kfp-webhooks.yml,
            kubeflow-pipelines-manifests.yml,
            legacy-v2-api-integration-tests.yml,
            pre-commit.yml,
            presubmit-backend.yml,
            publish-packages.yml,
            readthedocs-builds.yml,
            sdk-component-yaml.yml,
            sdk-docformatter.yml,
            sdk-isort.yml,
            sdk-upgrade.yml,
            sdk-yapf.yml,
            stable-merge-check.yml,
            stale.yml,
            tag-release-quay.yml,
            trivy.yml,
            unit-tests.yaml,
            upgrade-test.yml,
            validate-generated-files.yml