# Triage issues upon opening.
name: issue-triage.yml

on:
  issues:
    types: [opened]

jobs:
  on-issue-opened:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: gh issue comment ${{ github.event.issue.number }} --body "Thanks for opening this issue! A maintainer will triage it shortly."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
