# Validate
name: Gatekeeper

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  # Validate the linked issue in the PR body contains /ready command
  #todo: can anyone add "ready" or only approved users?
  validate-linked-issue:
    #todo: for the purposes of testing on my fork, I've disabled this check.
    #    if: |
    #      github.event.pull_request.author_association != 'MEMBER' &&
    #      github.event.pull_request.author_association != 'OWNER'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install PyGithub

      - name: Verify Linked Issue is Valid
        id: verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python3 .github/scripts/verify-pr-ready.py

      - name: Retrieve Workflow IDs if Validation Failed
        id: workflow-list
        if: steps.verify.outcome == 'failure'
        run: |
          ids=$(ls .github/workflows/ \
            | grep -v -e '^cancel\.yml$' -e '^pr-gatekeeper\.yml$' \
            | paste -sd ',' -)
          echo "ids=$ids" >> "$GITHUB_OUTPUT"

      - name: Cancel Workflows on Validation Failure
        id: cancel
        if: steps.verify.outcome == 'failure'
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: ${{ steps.workflow-list.outputs.ids }}


      # close PR on failure.
      - name: Close PR on failure
        if: always() && steps.verify.outcome == 'failure'
        run: gh pr close "${{ github.event.pull_request.number }}" --comment "Closing this PR automatically. Link an issue with 'ready' label in the PR body and then reopen. See https://github.com/decentraland/decentraland-node/blob/main/CONTRIBUTING.md#pull-requests for more details."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
